# Generated by Django 5.0.7 on 2025-10-04 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0006_paciente_altura_paciente_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameDicom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orthanc_study_id', models.CharField(help_text='ID do Estudo no Orthanc', max_length=255, unique=True)),
                ('study_description', models.CharField(blank=True, max_length=255, null=True)),
                ('study_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_dicom', to='pacientes.paciente')),
            ],
        ),
    ]
