# Generated by Django 5.2.5 on 2025-08-14 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamento', to='agendamentos.agendamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('CartaoCredito', 'Cartão de Crédrito'), ('CartaoDebito', 'Cartão de Débito'), ('PIX', 'PIX'), ('Convenio', 'Convênio')], max_length=20),
        ),
    ]
