# Generated by Django 5.0.7 on 2025-08-21 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0003_categoriadespesa_alter_pagamento_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='faturamento.convenio')),
            ],
            options={
                'ordering': ['convenio__nome', 'nome'],
                'unique_together': {('convenio', 'nome')},
            },
        ),
    ]
