# Generated by Django 5.0.7 on 2025-08-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0004_convenio_planoconvenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('CartaoCredito', 'Cartão de Crédito'), ('CartaoDebito', 'Cartão de Débito'), ('PIX', 'PIX'), ('Convenio', 'Convênio')], max_length=20, null=True),
        ),
    ]
