# Generated by Django 5.0.7 on 2025-08-23 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_alter_agendamento_paciente'),
        ('faturamento', '0005_pagamento_status_alter_pagamento_data_pagamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('valor_total_lote', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Aberto', 'Em Aberto'), ('Enviado', 'Enviado para o Convênio'), ('Pago', 'Pago'), ('Pago com Glosa', 'Pago com Glosa'), ('Recusado', 'Recusado')], default='Aberto', max_length=20)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='faturamento.convenio')),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mes_referencia'],
            },
        ),
        migrations.CreateModel(
            name='GuiaTiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_guia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_guia', models.CharField(default='Enviada', max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guia_tiss', to='agendamentos.agendamento')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='faturamento.lotefaturamento')),
            ],
        ),
    ]
