# Generated by Django 5.0.7 on 2025-09-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0007_procedimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='valor',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='valor_particular',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Particular (R$)'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ValorProcedimentoConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Acordado (R$)')),
                ('plano_convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_procedimento', to='faturamento.planoconvenio')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_convenio', to='faturamento.procedimento')),
            ],
            options={
                'verbose_name': 'Valor de Procedimento por Convênio',
                'verbose_name_plural': 'Valores de Procedimentos por Convênios',
                'unique_together': {('procedimento', 'plano_convenio')},
            },
        ),
    ]
