# Generated by Django 5.0.7 on 2025-09-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0008_remove_procedimento_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='inter_txid',
            field=models.CharField(blank=True, help_text='ID da transação gerado pelo Banco Inter', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='link_pagamento',
            field=models.URLField(blank=True, help_text='URL do link de pagamento para Cartão de Crédito', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pix_copia_e_cola',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pix_expira_em',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a cobrança PIX expira', null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pix_qr_code_base64',
            field=models.TextField(blank=True, help_text='Imagem do QR Code em formato base64', null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('CartaoCredito', 'Cartão de Crédito'), ('CartaoDebito', 'Cartão de Débito'), ('PIX', 'PIX'), ('Convenio', 'Convênio'), ('MaquinaCartao', 'Máquina de Cartão')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado'), ('Expirado', 'Expirado')], default='Pendente', max_length=20),
        ),
    ]
