# Generated by Django 5.0.7 on 2025-12-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0014_alter_pagamento_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data de vencimento para contas a receber', null=True),
        ),
    ]
