# Generated by Django 5.0.7 on 2026-01-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0015_despesa_data_pagamento_pagamento_data_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriadespesa',
            name='tipo',
            field=models.CharField(choices=[('Fixa', 'Fixa (Estrutura/Recorrente)'), ('Variavel', 'Variável (Consumo/Eventual)')], default='Variavel', help_text='Define se entra no cálculo de custo fixo ou variável', max_length=20),
        ),
    ]
