# Generated by Django 5.0.7 on 2026-02-08 21:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0014_agendamento_ciclo'),
        ('faturamento', '0018_despesa_numero_parcela_pagamento_numero_parcela_and_more'),
        ('pacientes', '0009_paciente_dum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriadespesa',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['-data_despesa']},
        ),
        migrations.AlterModelOptions(
            name='transacaofinanceira',
            options={'ordering': ['-data_vencimento']},
        ),
        migrations.AlterModelOptions(
            name='valorprocedimentoconvenio',
            options={'verbose_name': 'Valor de Procedimento por Convênio'},
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='numero_parcela',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='transacao_pai',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='numero_parcela',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='transacao_pai',
        ),
        migrations.RemoveField(
            model_name='transacaofinanceira',
            name='eh_recorrente',
        ),
        migrations.RemoveField(
            model_name='transacaofinanceira',
            name='frequencia',
        ),
        migrations.RemoveField(
            model_name='transacaofinanceira',
            name='valor_total_original',
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financeiro_unificado', to='agendamentos.agendamento'),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='data_competencia',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data do fato gerador (ex: data da consulta)'),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('PIX', 'PIX'), ('CartaoCredito', 'Cartão de Crédito'), ('CartaoDebito', 'Cartão de Débito'), ('Transferencia', 'Transferência Bancária'), ('Boleto', 'Boleto'), ('Convenio', 'Convênio'), ('MaquinaCartao', 'Máquina de Cartão'), ('Outro', 'Outro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='inter_txid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='link_pagamento',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='numero_parcela',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='pix_copia_e_cola',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='pix_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='pix_qr_code_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado'), ('Renegociado', 'Renegociado'), ('Liquidado', 'Liquidado')], default='Pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='transacao_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhas', to='faturamento.transacaofinanceira'),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='valor_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor original antes de juros/multa', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='categoriadespesa',
            name='tipo',
            field=models.CharField(choices=[('Fixa', 'Fixa (Estrutura/Recorrente)'), ('Variavel', 'Variável (Consumo/Eventual)')], default='Variavel', max_length=20),
        ),
        migrations.AlterField(
            model_name='lotefaturamento',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Em Aberto'), ('Enviado', 'Enviado'), ('Pago', 'Pago'), ('Pago com Glosa', 'Pago com Glosa'), ('Recusado', 'Recusado')], default='Aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamento_legado', to='agendamentos.agendamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('CartaoCredito', 'Cartão de Crédito'), ('CartaoDebito', 'Cartão de Débito'), ('PIX', 'PIX'), ('Convenio', 'Convênio'), ('MaquinaCartao', 'Máquina de Cartão'), ('Transferencia', 'Transferência Bancária'), ('Boleto', 'Boleto'), ('Outro', 'Outro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='inter_txid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='link_pagamento',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='pix_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='pix_qr_code_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado'), ('Expirado', 'Expirado'), ('Renegociado', 'Renegociado')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='codigo_tuss',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='valor_particular',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transacaofinanceira',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financeiro_unificado', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='valorprocedimentoconvenio',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='transacaofinanceira',
            index=models.Index(fields=['status', 'data_vencimento'], name='faturamento_status_5fcaa5_idx'),
        ),
        migrations.AddIndex(
            model_name='transacaofinanceira',
            index=models.Index(fields=['paciente'], name='faturamento_pacient_b34edd_idx'),
        ),
    ]
