# Generated by Django 5.0.7 on 2026-02-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0014_agendamento_ciclo'),
        ('faturamento', '0019_alter_categoriadespesa_options_alter_despesa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamento', to='agendamentos.agendamento'),
        ),
    ]
