# Generated by Django 5.0.7 on 2026-02-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0020_alter_pagamento_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('PIX', 'PIX'), ('CartaoCredito', 'Cartão de Crédito'), ('CartaoDebito', 'Cartão de Débito'), ('Transferencia', 'Transferência Bancária'), ('Boleto', 'Boleto'), ('Outro', 'Outro')], max_length=50, null=True),
        ),
    ]
