# Generated by Django 5.0.7 on 2026-04-02 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0021_despesa_forma_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='baixado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixas_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_hora_baixa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='baixado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixas_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transacaofinanceira',
            name='data_hora_baixa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
