# Generated by Django 5.0.7 on 2026-05-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0022_pagamento_baixado_por_pagamento_data_hora_baixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotefaturamento',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotefaturamento',
            name='valor_glosa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lotefaturamento',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
