[pytest]
# Aponta para o arquivo de configurações principal do seu projeto
DJANGO_SETTINGS_MODULE = core.settings

# Diz ao pytest quais padrões de nomes de arquivos ele deve procurar
python_files = tests.py test_*.py *_tests.py