# Generated by Django 5.0.7 on 2025-08-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_paciente_medico_responsavel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='convenio',
        ),
    ]
