# Generated by Django 5.0.7 on 2025-08-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_remove_paciente_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura em metros', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso em kg', max_digits=5, null=True),
        ),
    ]
