# Generated by Django 5.0.7 on 2025-10-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_altura_paciente_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf_responsavel',
            field=models.CharField(blank=True, help_text='CPF do responsável', max_length=14),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_responsavel',
            field=models.CharField(blank=True, help_text='Nome do responsável (se o paciente for menor)', max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone_responsavel',
            field=models.CharField(blank=True, help_text='Telefone do responsável (se diferente do principal)', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura em cm', max_digits=5, null=True),
        ),
    ]
