# Generated by Django 5.0.7 on 2026-02-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_alter_paciente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dum',
            field=models.DateField(blank=True, help_text='Data da Última Menstruação', null=True),
        ),
    ]
