# Generated by Django 5.0.7 on 2026-07-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_alter_paciente_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='contato_emergencia_nome',
            field=models.CharField(blank=True, help_text='Nome do contato de emergência', max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='contato_emergencia_parentesco',
            field=models.CharField(blank=True, help_text='Grau de parentesco (Ex: Mãe, Cônjuge)', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='contato_emergencia_telefone',
            field=models.CharField(blank=True, help_text='Telefone do contato de emergência', max_length=20),
        ),
    ]
