# Generated by Django 5.0.7 on 2026-07-24 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0023_lotefaturamento_data_pagamento_and_more'),
        ('pacientes', '0011_paciente_contato_emergencia_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para arquivar o paciente em vez de excluí-lo permanentemente.', verbose_name='Paciente Ativo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contato_emergencia_nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contato de Emergência'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contato_emergencia_parentesco',
            field=models.CharField(blank=True, max_length=50, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contato_emergencia_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone de Emergência'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF do Responsável'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dum',
            field=models.DateField(blank=True, help_text='Data da Última Menstruação', null=True, verbose_name='DUM'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=20, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medico_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'medico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to=settings.AUTH_USER_MODEL, verbose_name='Médico Responsável'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_completo',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_responsavel',
            field=models.CharField(blank=True, help_text='Obrigatório para menores', max_length=255, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_carteirinha',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nº da Carteirinha'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='plano_convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='faturamento.planoconvenio', verbose_name='Plano/Convênio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_celular',
            field=models.CharField(max_length=20, verbose_name='Telefone Celular'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do Responsável'),
        ),
    ]
