# Generated by Django 5.0.7 on 2025-08-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0006_lotefaturamento_guiatiss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tuss', models.CharField(help_text='Código do procedimento na tabela TUSS', max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
    ]
