# Generated by Django 5.0.7 on 2025-09-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0009_pagamento_inter_txid_pagamento_link_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='descricao_detalhada',
            field=models.TextField(blank=True, help_text='Texto completo que o chatbot usará para descrever o exame.', verbose_name='Descrição Detalhada para Chatbot'),
        ),
    ]
