# Generated by Django 5.0.7 on 2025-09-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0010_procedimento_descricao_detalhada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='descricao',
            field=models.CharField(blank=True, help_text='Descrição para lançamentos avulsos ou observações.', max_length=255, null=True),
        ),
    ]
