# Generated by Django 5.0.7 on 2025-12-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0011_pagamento_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimento',
            options={'ordering': ['categoria', 'descricao']},
        ),
        migrations.AddField(
            model_name='procedimento',
            name='categoria',
            field=models.CharField(choices=[('US_GERAL', 'Ultrassonografia Geral'), ('MED_FETAL', 'Medicina Fetal'), ('ECOCARDIOGRAMA', 'Ecocardiograma'), ('MUSCULO', 'Musculoesquelético'), ('DOPPLER', 'Doppler Vascular'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='codigo_tuss',
            field=models.CharField(help_text='Código do procedimento na tabela TUSS', max_length=20),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='descricao_detalhada',
            field=models.TextField(blank=True),
        ),
    ]
