# Generated by Django 5.0.7 on 2025-12-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0012_alter_procedimento_options_procedimento_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
