# Generated by Django 5.0.7 on 2025-12-29 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0013_despesa_data_vencimento_despesa_pago'),
        ('pacientes', '0007_paciente_cpf_responsavel_paciente_nome_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente'),
        ),
    ]
