# Generated by Django 5.0.7 on 2026-01-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0016_categoriadespesa_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='codigo_tuss',
            field=models.CharField(blank=True, help_text='Código do procedimento na tabela TUSS', max_length=20, null=True),
        ),
    ]
