# Generated by Django 5.0.7 on 2026-02-08 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0017_alter_procedimento_codigo_tuss'),
        ('pacientes', '0009_paciente_dum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='numero_parcela',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='numero_parcela',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TransacaoFinanceira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], max_length=20)),
                ('valor_total_original', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qtd_parcelas', models.IntegerField(default=1)),
                ('eh_recorrente', models.BooleanField(default=False)),
                ('frequencia', models.CharField(blank=True, choices=[('Mensal', 'Mensal'), ('Semanal', 'Semanal')], max_length=20, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='faturamento.categoriadespesa')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='transacao_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_despesa', to='faturamento.transacaofinanceira'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='transacao_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_receita', to='faturamento.transacaofinanceira'),
        ),
    ]
