# Generated by Django 5.2.4 on 2025-08-13 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_paciente_medico_responsavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('queixa_principal', models.TextField(blank=True)),
                ('historia_doenca_atual', models.TextField(blank=True)),
                ('historico_medico_pregresso', models.TextField(blank=True)),
                ('historico_familiar', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('medicamentos_em_uso', models.TextField(blank=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('tipo_atestado', models.CharField(choices=[('Comparecimento', 'Atestado de Comparecimento'), ('Afastamento', 'Atestado de Afastamento'), ('Aptidao', 'Atestado de Aptidão Física')], max_length=20)),
                ('observacoes', models.TextField(help_text='Texto do atestado, incluindo informações como CID, dias de afastamento, etc.')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('notas_subjetivas', models.TextField(verbose_name='Subjetivo (S)')),
                ('notas_objetivas', models.TextField(verbose_name='Objetivo (O)')),
                ('avaliacao', models.TextField(verbose_name='Avaliação (A)')),
                ('plano', models.TextField(verbose_name='Plano (P)')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-data_atendimento'],
            },
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prescricao', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-data_prescricao'],
            },
        ),
        migrations.CreateModel(
            name='ItemPrescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200)),
                ('dosagem', models.CharField(max_length=100)),
                ('instrucoes', models.TextField(verbose_name='Instruções de Uso')),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='prontuario.prescricao')),
            ],
        ),
    ]
