# Generated by Django 5.0.7 on 2025-10-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0002_documentopaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text="Ex: 'Dor precordial tipo aperto'", max_length=255)),
                ('especialidade', models.CharField(choices=[('Cardiologia', 'Cardiologia'), ('Ginecologia', 'Ginecologia'), ('Neonatologia', 'Neonatologia'), ('Obstetricia', 'Obstetrícia'), ('Ortopedia', 'Ortopedia'), ('Pediatria', 'Pediatria'), ('Reumatologia', 'Reumatologia'), ('Reumatologia Pediatrica', 'Reumatologia Pediátrica')], db_index=True, max_length=50)),
                ('area_clinica', models.CharField(choices=[('QUEIXA_PRINCIPAL', 'Queixa Principal'), ('HDA', 'História da Doença Atual'), ('HMP', 'História Médica Pregressa'), ('EXAME_FISICO_GERAL', 'Exame Físico - Geral'), ('EXAME_FISICO_CARDIO', 'Exame Físico - Cardiovascular'), ('EXAME_FISICO_RESP', 'Exame Físico - Respiratório'), ('EXAME_FISICO_ORTO', 'Exame Físico - Ortopédico')], db_index=True, max_length=50, verbose_name='Área do Prontuário')),
            ],
            options={
                'verbose_name': 'Opção Clínica',
                'verbose_name_plural': 'Opções Clínicas',
                'ordering': ['especialidade', 'area_clinica', 'descricao'],
                'unique_together': {('descricao', 'especialidade', 'area_clinica')},
            },
        ),
    ]
