# Generated by Django 5.0.7 on 2025-10-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0004_popular_opcoes_clinicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucao',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='exames_complementares',
            field=models.TextField(blank=True, null=True, verbose_name='ECG, Eco, Laboratoriais, etc.'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='frequencia_cardiaca',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frequência Cardíaca (bpm)'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='pressao_arterial',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pressão Arterial'),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='avaliacao',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico / Hipóteses'),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='notas_objetivas',
            field=models.TextField(blank=True, null=True, verbose_name='Ausculta Cardíaca/Pulmonar, Sinais, etc.'),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='notas_subjetivas',
            field=models.TextField(blank=True, null=True, verbose_name='Subjetivo (Queixa Principal / HDA)'),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='plano',
            field=models.TextField(blank=True, null=True, verbose_name='Plano Terapêutico / Condutas'),
        ),
    ]
