# Generated by Django 5.0.7 on 2025-10-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0005_evolucao_altura_evolucao_exames_complementares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucao',
            name='exames_complementares',
            field=models.TextField(blank=True, null=True, verbose_name='Exames Complementares (ECG, Eco, etc.)'),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='notas_objetivas',
            field=models.TextField(blank=True, null=True, verbose_name='Exame Físico (Ausculta, Sinais, etc.)'),
        ),
        migrations.AlterField(
            model_name='opcaoclinica',
            name='especialidade',
            field=models.CharField(choices=[('Cardiologia', 'Cardiologia'), ('Ginecologia', 'Ginecologia'), ('Neonatologia', 'Neonatologia'), ('Obstetrícia', 'Obstetrícia'), ('Ortopedia', 'Ortopedia'), ('Pediatria', 'Pediatria'), ('Reumatologia', 'Reumatologia'), ('Reumatologia Pediátrica', 'Reumatologia Pediátrica')], db_index=True, max_length=50),
        ),
    ]
