# Generated by Django 5.0.7 on 2025-10-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0006_alter_evolucao_exames_complementares_and_more'),
        ('prontuario', '0007_carregar_opcoes_cardiologia'),
    ]

    operations = [
    ]
