# Generated by Django 5.0.7 on 2025-10-10 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0008_merge_20251009_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamneseGinecologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dum', models.DateField(blank=True, null=True, verbose_name='Data da Última Menstruação (DUM)')),
                ('menarca_idade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade da Menarca')),
                ('gesta', models.PositiveIntegerField(blank=True, null=True, verbose_name='Gesta (nº de gestações)')),
                ('para', models.PositiveIntegerField(blank=True, null=True, verbose_name='Para (nº de partos)')),
                ('abortos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Abortos (nº)')),
                ('antecedentes_ginecologicos', models.TextField(blank=True, null=True, verbose_name='Antecedentes Ginecológicos')),
                ('antecedentes_obstetricos', models.TextField(blank=True, null=True, verbose_name='Antecedentes Obstétricos')),
                ('anamnese', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ginecologica', to='prontuario.anamnese')),
            ],
            options={
                'verbose_name': 'Anamnese Ginecológica',
                'verbose_name_plural': 'Anamneses Ginecológicas',
            },
        ),
    ]
