# Generated by Django 5.0.7 on 2025-10-18 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0009_anamneseginecologica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anamneseginecologica',
            options={},
        ),
        migrations.RemoveField(
            model_name='anamneseginecologica',
            name='antecedentes_ginecologicos',
        ),
        migrations.RemoveField(
            model_name='anamneseginecologica',
            name='antecedentes_obstetricos',
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='cesareas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cesáreas (C)'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='ciclo_duracao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duração do Ciclo'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='ciclo_intervalo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Intervalo do Ciclo'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='ciclo_regular',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('irregular', 'Irregular')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='complicacoes_obstetricas',
            field=models.TextField(blank=True, null=True, verbose_name='Complicações Obstétricas Anteriores'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='dismenorreia',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='ex_abdome',
            field=models.TextField(blank=True, null=True, verbose_name='Exame Abdominal'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='ex_especular',
            field=models.TextField(blank=True, null=True, verbose_name='Exame Especular'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='ex_genitais_externos',
            field=models.TextField(blank=True, null=True, verbose_name='Exame Genitais Externos'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='ex_mamas',
            field=models.TextField(blank=True, null=True, verbose_name='Exame das Mamas'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='ex_toque',
            field=models.TextField(blank=True, null=True, verbose_name='Toque Vaginal Bimanual'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='fc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frequência Cardíaca (bpm)'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='hists_ists',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico de ISTs'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='mac_anterior',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Métodos Anteriores'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='mac_atual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Método Contraceptivo Atual'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='pa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pressão Arterial (mmHg)'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='sintomas',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='ultima_mamografia_data',
            field=models.DateField(blank=True, null=True, verbose_name='Última Mamografia (Data)'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='ultima_mamografia_resultado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Resultado Mamografia'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='ultimo_preventivo_data',
            field=models.DateField(blank=True, null=True, verbose_name='Último Preventivo (Data)'),
        ),
        migrations.AddField(
            model_name='anamneseginecologica',
            name='ultimo_preventivo_resultado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Resultado Preventivo'),
        ),
        migrations.AlterField(
            model_name='anamneseginecologica',
            name='abortos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Abortos (A)'),
        ),
        migrations.AlterField(
            model_name='anamneseginecologica',
            name='dum',
            field=models.DateField(blank=True, null=True, verbose_name='DUM'),
        ),
        migrations.AlterField(
            model_name='anamneseginecologica',
            name='gesta',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gesta (G)'),
        ),
        migrations.AlterField(
            model_name='anamneseginecologica',
            name='para',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Para (P)'),
        ),
        migrations.CreateModel(
            name='AnamneseCardiologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.JSONField(blank=True, default=dict, null=True)),
                ('fatores_risco', models.JSONField(blank=True, default=dict, null=True)),
                ('pa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pressão Arterial (mmHg)')),
                ('fc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frequência Cardíaca (bpm)')),
                ('ictus_cordis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ictus Cordis')),
                ('ausculta_cardiaca', models.TextField(blank=True, null=True, verbose_name='Ausculta Cardíaca')),
                ('pulsos', models.TextField(blank=True, null=True, verbose_name='Pulsos Periféricos')),
                ('exame_fisico_outros', models.TextField(blank=True, null=True, verbose_name='Outros Achados Exame Físico')),
                ('medicamentos_em_uso', models.TextField(blank=True, null=True, verbose_name='Medicamentos Cardiológicos em Uso')),
                ('historico_familiar', models.TextField(blank=True, null=True, verbose_name='Histórico Familiar Cardiológico')),
                ('anamnese', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardiologica', to='prontuario.anamnese')),
            ],
        ),
        migrations.CreateModel(
            name='AnamneseNeonatologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade_materna', models.PositiveIntegerField(blank=True, null=True)),
                ('gpa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gesta/Para/Aborto')),
                ('tipo_sanguineo_mae', models.CharField(blank=True, max_length=5, null=True)),
                ('coombs_indireto', models.CharField(blank=True, max_length=50, null=True)),
                ('sorologias', models.JSONField(blank=True, default=dict, null=True)),
                ('intercorrencias_gestacao', models.TextField(blank=True, null=True)),
                ('tipo_parto', models.CharField(blank=True, max_length=50, null=True)),
                ('idade_gestacional', models.CharField(blank=True, max_length=50, null=True)),
                ('bolsa_rota', models.CharField(blank=True, max_length=100, null=True)),
                ('liquido_amniotico', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_nascimento', models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso ao Nascer (g)')),
                ('comprimento', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Comprimento (cm)')),
                ('pc', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Perímetro Cefálico (cm)')),
                ('apgar', models.CharField(blank=True, max_length=10, null=True, verbose_name='APGAR (1º/5º)')),
                ('reanimacao', models.TextField(blank=True, null=True, verbose_name='Reanimação em Sala de Parto')),
                ('triagens', models.JSONField(blank=True, default=dict, null=True)),
                ('ex_estado_geral', models.TextField(blank=True, null=True)),
                ('ex_pele', models.TextField(blank=True, null=True)),
                ('ex_cabeca', models.TextField(blank=True, null=True)),
                ('ex_resp', models.TextField(blank=True, null=True)),
                ('ex_cardio', models.TextField(blank=True, null=True)),
                ('ex_abdome', models.TextField(blank=True, null=True)),
                ('ex_genitalia', models.TextField(blank=True, null=True)),
                ('ex_neuro', models.TextField(blank=True, null=True)),
                ('alimentacao', models.CharField(blank=True, max_length=20, null=True)),
                ('diurese', models.CharField(blank=True, max_length=50, null=True)),
                ('evacuacao', models.CharField(blank=True, max_length=50, null=True)),
                ('plano', models.TextField(blank=True, null=True, verbose_name='Plano e Observações')),
                ('anamnese', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neonatologia', to='prontuario.anamnese')),
            ],
            options={
                'verbose_name': 'Anamnese Neonatal',
                'verbose_name_plural': 'Anamneses Neonatais',
            },
        ),
        migrations.CreateModel(
            name='AnamneseOrtopedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.JSONField(blank=True, default=dict, null=True)),
                ('antecedentes', models.TextField(blank=True, null=True, verbose_name='Antecedentes Ortopédicos')),
                ('ex_local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local Afetado / Articulação')),
                ('ex_inspecao', models.TextField(blank=True, null=True, verbose_name='Inspeção')),
                ('ex_palpacao', models.TextField(blank=True, null=True, verbose_name='Palpação')),
                ('ex_adm', models.TextField(blank=True, null=True, verbose_name='Amplitude de Movimento (ADM)')),
                ('ex_forca', models.TextField(blank=True, null=True, verbose_name='Força Muscular (0-5)')),
                ('ex_neurovascular', models.TextField(blank=True, null=True, verbose_name='Exame Neurovascular')),
                ('ex_testes', models.TextField(blank=True, null=True, verbose_name='Testes Especiais')),
                ('anamnese', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ortopedica', to='prontuario.anamnese')),
            ],
        ),
        migrations.CreateModel(
            name='AnamnesePediatria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parto', models.CharField(blank=True, max_length=50, null=True)),
                ('idade_gestacional', models.CharField(blank=True, max_length=50, null=True)),
                ('peso_nascimento', models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso ao Nascer (g)')),
                ('apgar', models.CharField(blank=True, max_length=10, null=True, verbose_name='APGAR (1º/5º)')),
                ('intercorrencias_gestacao_parto', models.TextField(blank=True, null=True)),
                ('aleitamento', models.CharField(blank=True, max_length=20, null=True)),
                ('introducao_alimentar', models.TextField(blank=True, null=True)),
                ('vacinacao', models.CharField(blank=True, max_length=20, null=True)),
                ('vacinacao_obs', models.TextField(blank=True, null=True)),
                ('dnpm', models.JSONField(blank=True, default=dict, null=True)),
                ('sintomas', models.JSONField(blank=True, default=dict, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso Atual (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Altura Atual (cm)')),
                ('pc', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Perímetro Cefálico (cm)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('estado_geral', models.TextField(blank=True, null=True)),
                ('oroscopia', models.TextField(blank=True, null=True)),
                ('ausculta_resp', models.TextField(blank=True, null=True)),
                ('ausculta_card', models.TextField(blank=True, null=True)),
                ('abdome', models.TextField(blank=True, null=True)),
                ('pele_faneros', models.TextField(blank=True, null=True)),
                ('anamnese', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pediatrica', to='prontuario.anamnese')),
            ],
        ),
    ]
