# Generated by Django 5.0.7 on 2025-10-26 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_paciente_cpf_responsavel_paciente_nome_responsavel_and_more'),
        ('prontuario', '0010_alter_anamneseginecologica_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcoDNPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marco_id', models.CharField(db_index=True, max_length=100)),
                ('marco_descricao', models.CharField(max_length=255)),
                ('idade_marco', models.CharField(max_length=10)),
                ('alcançado', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcos_dnpm', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Marco de DNPM',
                'verbose_name_plural': 'Marcos de DNPM',
                'ordering': ['paciente', 'data_registro'],
            },
        ),
        migrations.CreateModel(
            name='VacinaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vacina', models.CharField(db_index=True, max_length=100)),
                ('idade_recomendada', models.CharField(max_length=20)),
                ('dose', models.CharField(max_length=50)),
                ('data_aplicacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aplicada', 'Aplicada'), ('Atrasada', 'Atrasada'), ('Não se aplica', 'Não se aplica')], default='Pendente', max_length=20)),
                ('observacao', models.TextField(blank=True, help_text='Ex: Rede privada, lote, etc.', null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Vacina do Paciente',
                'verbose_name_plural': 'Vacinas do Paciente',
                'ordering': ['paciente', 'idade_recomendada', 'nome_vacina'],
            },
        ),
    ]
