# Generated by Django 5.0.7 on 2025-10-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0011_marcodnpm_vacinapaciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnesecardiologia',
            name='ausculta_cardiaca',
        ),
        migrations.RemoveField(
            model_name='anamnesecardiologia',
            name='exame_fisico_outros',
        ),
        migrations.RemoveField(
            model_name='anamnesecardiologia',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='anamnesecardiologia',
            name='ictus_cordis',
        ),
        migrations.RemoveField(
            model_name='anamnesecardiologia',
            name='pa',
        ),
        migrations.RemoveField(
            model_name='anamnesecardiologia',
            name='pulsos',
        ),
        migrations.RemoveField(
            model_name='anamnesecardiologia',
            name='sintomas',
        ),
        migrations.AddField(
            model_name='anamnesecardiologia',
            name='cirurgias_cardiacas_previas',
            field=models.TextField(blank=True, null=True, verbose_name='Cirurgias Prévias (Ex: CRM, Angioplastia)'),
        ),
        migrations.AddField(
            model_name='anamnesecardiologia',
            name='comorbidades_outras',
            field=models.TextField(blank=True, null=True, verbose_name='Outras Comorbidades (Ex: DRC, DPOC)'),
        ),
        migrations.AddField(
            model_name='anamnesecardiologia',
            name='habito_atividade_fisica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atividade Física'),
        ),
        migrations.AddField(
            model_name='anamnesecardiologia',
            name='habito_etilismo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etilismo (frequência, tipo)'),
        ),
        migrations.AddField(
            model_name='anamnesecardiologia',
            name='habito_tabagismo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tabagismo (carga tabágica)'),
        ),
        migrations.AlterField(
            model_name='anamnesecardiologia',
            name='fatores_risco',
            field=models.JSONField(blank=True, default=dict, help_text="Ex: { 'has': true, 'dm': false, 'sahos': true }", null=True),
        ),
        migrations.AlterField(
            model_name='anamnesecardiologia',
            name='historico_familiar',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico Familiar Cardiológico (Ex: DAC precoce)'),
        ),
    ]
