# Generated by Django 5.0.7 on 2025-10-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0012_remove_anamnesecardiologia_ausculta_cardiaca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamneseneonatologia',
            name='alimentacao',
        ),
        migrations.RemoveField(
            model_name='anamneseneonatologia',
            name='diurese',
        ),
        migrations.RemoveField(
            model_name='anamneseneonatologia',
            name='evacuacao',
        ),
        migrations.RemoveField(
            model_name='anamneseneonatologia',
            name='ex_abdome',
        ),
        migrations.RemoveField(
            model_name='anamneseneonatologia',
            name='ex_cabeca',
        ),
        migrations.RemoveField(
            model_name='anamneseneonatologia',
            name='ex_cardio',
        ),
        migrations.RemoveField(
            model_name='anamneseneonatologia',
            name='ex_estado_geral',
        ),
        migrations.RemoveField(
            model_name='anamneseneonatologia',
            name='ex_genitalia',
        ),
        migrations.RemoveField(
            model_name='anamneseneonatologia',
            name='ex_neuro',
        ),
        migrations.RemoveField(
            model_name='anamneseneonatologia',
            name='ex_pele',
        ),
        migrations.RemoveField(
            model_name='anamneseneonatologia',
            name='ex_resp',
        ),
        migrations.RemoveField(
            model_name='anamneseneonatologia',
            name='pc',
        ),
        migrations.RemoveField(
            model_name='anamneseneonatologia',
            name='plano',
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='pc_nascimento',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='PC ao Nascer (cm)'),
        ),
    ]
