# Generated by Django 5.0.7 on 2025-10-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0013_remove_anamneseneonatologia_alimentacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamneseginecologica',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='anamneseginecologica',
            name='ex_abdome',
        ),
        migrations.RemoveField(
            model_name='anamneseginecologica',
            name='ex_especular',
        ),
        migrations.RemoveField(
            model_name='anamneseginecologica',
            name='ex_genitais_externos',
        ),
        migrations.RemoveField(
            model_name='anamneseginecologica',
            name='ex_mamas',
        ),
        migrations.RemoveField(
            model_name='anamneseginecologica',
            name='ex_toque',
        ),
        migrations.RemoveField(
            model_name='anamneseginecologica',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='anamneseginecologica',
            name='pa',
        ),
        migrations.RemoveField(
            model_name='anamneseginecologica',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='anamneseginecologica',
            name='sintomas',
        ),
    ]
