# Generated by Django 5.0.7 on 2025-10-28 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0014_remove_anamneseginecologica_altura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamneseClinicaGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmp', models.TextField(blank=True, null=True, verbose_name='Histórico Médico Pregresso')),
                ('habitos_sociais', models.TextField(blank=True, null=True, verbose_name='Hábitos e Histórico Social (Tabagismo, Etilismo, Ocupação, etc.)')),
                ('vacina_adulto_status', models.TextField(blank=True, null=True, verbose_name='Status Vacinal (Adulto)')),
                ('anamnese', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinica_geral', to='prontuario.anamnese')),
            ],
            options={
                'verbose_name': 'Anamnese Clínica Geral',
                'verbose_name_plural': 'Anamneses Clínica Geral',
            },
        ),
    ]
