# Generated by Django 5.0.7 on 2025-10-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0015_anamneseclinicageral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnesepediatria',
            name='abdome',
        ),
        migrations.RemoveField(
            model_name='anamnesepediatria',
            name='aleitamento',
        ),
        migrations.RemoveField(
            model_name='anamnesepediatria',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='anamnesepediatria',
            name='ausculta_card',
        ),
        migrations.RemoveField(
            model_name='anamnesepediatria',
            name='ausculta_resp',
        ),
        migrations.RemoveField(
            model_name='anamnesepediatria',
            name='estado_geral',
        ),
        migrations.RemoveField(
            model_name='anamnesepediatria',
            name='introducao_alimentar',
        ),
        migrations.RemoveField(
            model_name='anamnesepediatria',
            name='oroscopia',
        ),
        migrations.RemoveField(
            model_name='anamnesepediatria',
            name='pc',
        ),
        migrations.RemoveField(
            model_name='anamnesepediatria',
            name='pele_faneros',
        ),
        migrations.RemoveField(
            model_name='anamnesepediatria',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='anamnesepediatria',
            name='sintomas',
        ),
        migrations.RemoveField(
            model_name='anamnesepediatria',
            name='temperatura',
        ),
        migrations.AddField(
            model_name='anamnesepediatria',
            name='alimentacao_0_6m',
            field=models.JSONField(blank=True, default=dict, help_text='JSON com chaves: tipo_aleitamento (AME/Misto/Formula), pega (Boa/Parcial/Ruim), succao (Eficaz/Fraca/Ausente), diurese (Adequada/Reduzida), evacuacao (Normal/Ressecada/Diarreica), suplementacao (Vitamina/Ferro/Nenhuma)', null=True),
        ),
        migrations.AddField(
            model_name='anamnesepediatria',
            name='alimentacao_0_6m_obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Alimentação 0-6m'),
        ),
        migrations.AddField(
            model_name='anamnesepediatria',
            name='alimentacao_6_12m',
            field=models.JSONField(blank=True, default=dict, help_text='JSON com chaves: tipo_alimentacao (Mantem AM/Formula/Ambos), refeicoes_dia (2/3/>3), textura (Amassada/Picada/Pedaços), aceitacao (Boa/Parcial/Ruim), agua (Adequada/Baixa), suplementacao (VitD/Ferro/Nenhuma), aceitacao_geral (Adequada/Seletiva/Dificuldade Textura)', null=True),
        ),
        migrations.AddField(
            model_name='anamnesepediatria',
            name='alimentacao_6_12m_obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Alimentação 6-12m'),
        ),
        migrations.AddField(
            model_name='anamnesepediatria',
            name='copo_transicao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Copo de Transição'),
        ),
        migrations.AddField(
            model_name='anamnesepediatria',
            name='metodo_ia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Método Introdução Alimentar (Tradicional/BLW/BLISS/Misto)'),
        ),
        migrations.AddField(
            model_name='anamnesepediatria',
            name='sono_comportamento',
            field=models.JSONField(blank=True, default=dict, help_text='JSON com chaves: sono_diurno (Adequado/Alterado), sono_noturno (Adequado/Alterado), colica (Adequado/Alterado), choro (Adequado/Alterado), vinculo (Adequado/Alterado)', null=True),
        ),
        migrations.AddField(
            model_name='anamnesepediatria',
            name='sono_comportamento_obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Sono/Comportamento'),
        ),
        migrations.AlterField(
            model_name='anamnesepediatria',
            name='dnpm',
            field=models.JSONField(blank=True, default=dict, help_text='Resumo dos marcos principais', null=True),
        ),
        migrations.AlterField(
            model_name='anamnesepediatria',
            name='vacinacao',
            field=models.CharField(blank=True, help_text='Resumo: Em dia / Atrasada', max_length=20, null=True),
        ),
    ]
