# Generated by Django 5.0.7 on 2025-10-31 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_paciente_cpf_responsavel_paciente_nome_responsavel_and_more'),
        ('prontuario', '0016_remove_anamnesepediatria_abdome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('especialidade', models.CharField(choices=[('cardiologia', 'Cardiologia'), ('pediatria', 'Pediatria'), ('geral', 'Geral')], default='geral', max_length=100)),
                ('conteudo', models.TextField()),
                ('medico_criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo_final', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prontuario.evolucao')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='pacientes.paciente')),
                ('template_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prontuario.templaterelatorio')),
            ],
            options={
                'verbose_name': 'Relatório Salvo',
                'verbose_name_plural': 'Relatórios Salvos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
