# Generated by Django 5.0.7 on 2025-11-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0017_templaterelatorio_relatoriosalvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='antibioticos',
            field=models.TextField(blank=True, null=True, verbose_name='Antibióticos (Esquema/Dias)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='corticoterapia',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Corticoterapia'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='diagnosticos_principais',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnósticos Principais na Alta'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='exames_realizados',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Exames Hospitalares (US-TF, Eco, etc.)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='fototerapia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fototerapia (dias)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='ig_classificacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Classificação IG'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='neuroprotecao_mg',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Neuroproteção (Sulf. Magnésio)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='npp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NPP (dias)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='peso_classificacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adequação Peso'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='pre_natal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pré-Natal'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='suporte_ventilatorio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Suporte Ventilatório (VM/CPAP/O2)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='tempo_internacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tempo de Internação (dias)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='tipo_gestacao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo Gestação'),
        ),
        migrations.AlterField(
            model_name='anamneseneonatologia',
            name='apgar',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="APGAR (1º/5º/10')"),
        ),
        migrations.AlterField(
            model_name='anamneseneonatologia',
            name='reanimacao',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Reanimação em Sala de Parto (JSON)'),
        ),
    ]
