# Generated by Django 5.0.7 on 2025-11-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0018_anamneseneonatologia_antibioticos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='outros_exames',
            field=models.JSONField(blank=True, default=list, verbose_name='Lista de Outros Exames'),
        ),
    ]
