# Generated by Django 5.0.7 on 2025-11-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0019_anamneseneonatologia_outros_exames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnesepediatria',
            name='apgar',
        ),
        migrations.AddField(
            model_name='anamnesepediatria',
            name='apgar_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='APGAR 1º Min'),
        ),
        migrations.AddField(
            model_name='anamnesepediatria',
            name='apgar_10',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='APGAR 10º Min'),
        ),
        migrations.AddField(
            model_name='anamnesepediatria',
            name='apgar_5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='APGAR 5º Min'),
        ),
        migrations.AddField(
            model_name='vacinapaciente',
            name='vacina_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
