# Generated by Django 5.0.7 on 2025-11-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0020_remove_anamnesepediatria_apgar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucao',
            name='especialidade',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Especialidade da Consulta'),
        ),
    ]
