# Generated by Django 5.0.7 on 2025-11-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0021_evolucao_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesecardiologia',
            name='fatores_risco',
            field=models.TextField(blank=True, null=True, verbose_name='Fatores de Risco (Texto)'),
        ),
    ]
