# Generated by Django 5.0.7 on 2025-11-16 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0012_bloqueioagenda'),
        ('prontuario', '0022_alter_anamnesecardiologia_fatores_risco'),
        ('usuarios', '0009_customuser_bairro_customuser_cep_customuser_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucao',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolucao', to='agendamentos.agendamento'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='especialidade_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.especialidade', verbose_name='Especialidade (Novo Link)'),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='especialidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Especialidade (Texto Antigo)'),
        ),
    ]
