# Generated by Django 5.0.7 on 2025-11-16 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0024_migrar_especialidades_para_fk'),
        ('usuarios', '0009_customuser_bairro_customuser_cep_customuser_cidade_and_more'),
    ]

    # --- ★★★ ESTE É O BLOCO CORRIGIDO ★★★ ---
    operations = [
        # 1. Remova o campo de TEXTO antigo ('especialidade')
        migrations.RemoveField(
            model_name='evolucao',
            name='especialidade',
        ),
        # 2. Renomeie o campo de ID ('especialidade_link') para o nome final
        migrations.RenameField(
            model_name='evolucao',
            old_name='especialidade_link',
            new_name='especialidade',
        ),
    ]
    # --- FIM DO BLOCO CORRIGIDO ---