# Generated by Django 5.0.7 on 2025-11-17 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0025_remove_evolucao_especialidade_link_and_more'),
        ('usuarios', '0009_customuser_bairro_customuser_cep_customuser_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamneseneonatologia',
            name='neuroprotecao_mg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Neuroproteção (Sulf. Magnésio)'),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.especialidade', verbose_name='Especialidade da Consulta'),
        ),
    ]
