# Generated by Django 5.0.7 on 2025-12-07 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_paciente_cpf_responsavel_paciente_nome_responsavel_and_more'),
        ('prontuario', '0026_alter_anamneseneonatologia_neuroprotecao_mg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_exame', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('texto_laudo', models.TextField()),
                ('dados_estruturados', models.JSONField(blank=True, default=dict, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='FINALIZADO', max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudos_prontuario', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemLaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='laudos_imagens/%Y/%m/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='prontuario.laudo')),
            ],
        ),
    ]
