# Generated by Django 5.0.7 on 2026-02-07 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_exame_ciclo'),
        ('prontuario', '0027_laudo_imagemlaudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='exame',
            field=models.OneToOneField(blank=True, help_text='Vínculo com os arquivos/imagens e credenciais da paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laudo_medico', to='exames.exame'),
        ),
    ]
