# Generated by Django 5.0.7 on 2026-02-07 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0014_agendamento_ciclo'),
        ('exames', '0003_exame_ciclo'),
        ('prontuario', '0028_laudo_exame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloLaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('codigo_mnemonico', models.CharField(blank=True, max_length=50, null=True)),
                ('conteudo_padrao', models.JSONField(blank=True, default=dict)),
                ('texto_padrao_html', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='laudo',
            old_name='titulo',
            new_name='titulo_exame',
        ),
        migrations.AddField(
            model_name='laudo',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laudo_prontuario', to='agendamentos.agendamento'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='laudos_assinados/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='codigo_acesso',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='laudo',
            name='crm_medico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='laudo',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='laudo',
            name='imagens_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='laudo',
            name='medico_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laudo',
            name='senha_acesso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='dados_estruturados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='exame',
            field=models.OneToOneField(blank=True, help_text='Vínculo com os arquivos e credenciais do portal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laudo_prontuario_vinculo', to='exames.exame'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laudos_assinados_prontuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='texto_laudo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='tipo_exame',
            field=models.CharField(default='OBSTETRICO', max_length=50),
        ),
    ]
