# Generated by Django 5.0.7 on 2026-03-20 12:43

import prontuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0029_modelolaudo_rename_titulo_laudo_titulo_exame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to=prontuario.models.upload_laudo_pdf_path),
        ),
    ]
