# Generated by Django 5.0.7 on 2026-04-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0030_alter_laudo_arquivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PROCESSANDO', 'Processando'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20),
        ),
    ]
