# Generated by Django 5.0.7 on 2026-05-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0031_alter_laudo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PROCESSANDO', 'Processando'), ('FINALIZADO', 'Finalizado'), ('ERRO', 'Erro'), ('CANCELADO_POR_RETIFICACAO', 'Cancelado (Retificado)')], default='RASCUNHO', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacinapaciente',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aplicada', 'Aplicada'), ('Atrasada', 'Atrasada'), ('Não se aplica', 'Não se aplica')], default='Pendente', max_length=50),
        ),
    ]
