# Generated by Django 5.0.7 on 2026-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0032_alter_laudo_status_alter_vacinapaciente_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescricao',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título da Prescrição'),
        ),
    ]
