# Generated by Django 5.0.7 on 2026-06-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0033_prescricao_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcodnpm',
            name='alcançado',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
