# Generated by Django 5.0.7 on 2026-06-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0034_alter_marcodnpm_alcançado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucao',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm/m)'),
        ),
    ]
