# Generated by Django 5.0.7 on 2026-06-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0035_alter_evolucao_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucao',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Peso (kg)'),
        ),
    ]
