# Generated by Django 5.0.7 on 2026-06-28 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0036_alter_evolucao_peso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloPrescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Modelo')),
                ('itens', models.JSONField(default=list, help_text='Lista de medicamentos e instruções do modelo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_prescricao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo de Prescrição',
                'verbose_name_plural': 'Modelos de Prescrição',
                'ordering': ['titulo'],
            },
        ),
    ]
