# Generated by Django 5.0.7 on 2026-06-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0037_modeloprescricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprescricao',
            name='via',
            field=models.CharField(default='Oral', max_length=50),
        ),
    ]
