# Generated by Django 5.0.7 on 2026-06-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0038_itemprescricao_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='atestado',
            name='cid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código CID-10'),
        ),
        migrations.AddField(
            model_name='atestado',
            name='paciente_autorizou_cid',
            field=models.BooleanField(default=False, verbose_name='Paciente autorizou CID'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='cid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código CID-10'),
        ),
    ]
