# Generated by Django 5.0.7 on 2026-06-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0039_atestado_cid_atestado_paciente_autorizou_cid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriosalvo',
            name='cid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código CID-10'),
        ),
        migrations.AddField(
            model_name='relatoriosalvo',
            name='paciente_autorizou_cid',
            field=models.BooleanField(default=False, verbose_name='Paciente autorizou CID'),
        ),
    ]
