# Generated by Django 5.0.7 on 2026-07-14 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0040_relatoriosalvo_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atestado',
            name='data_emissao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
