# Generated by Django 5.0.7 on 2026-07-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0041_alter_atestado_data_emissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atestado',
            name='assinatura_institucional',
            field=models.BooleanField(default=False, verbose_name='Assinatura institucional (emitido pela recepção, sem CRM)'),
        ),
    ]
