# Generated by Django 5.0.7 on 2026-07-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0042_atestado_assinatura_institucional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atestado',
            name='tipo_atestado',
            field=models.CharField(choices=[('Comparecimento', 'Declaração de Comparecimento'), ('Afastamento', 'Atestado de Afastamento'), ('Aptidao', 'Atestado de Aptidão Física')], max_length=20),
        ),
    ]
