# Generated by Django 5.0.7 on 2026-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0043_alter_atestado_tipo_atestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='anti_d',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Recebeu Anti-D'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='antibioticos_d',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Antibióticos (dias)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='antibioticos_esquema',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Esquema Antibiótico'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='apgar_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='APGAR 1º Min'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='apgar_10',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='APGAR 10º Min'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='apgar_5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='APGAR 5º Min'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='comorbidades_detalhes',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Comorbidades Maternas (JSON)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='comorbidades_outras_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição de Outras Comorbidades'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='condicoes_maternas',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Condições Maternas (Sim/Não)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='coombs_direto_rn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Coombs Direto RN'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='eco_data',
            field=models.DateField(blank=True, null=True, verbose_name='Ecocardiograma (Data)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='eco_resultado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ecocardiograma (Resultado)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='eluato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Eluato'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='fototerapia_d',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fototerapia (dias)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='fundo_olho_data',
            field=models.DateField(blank=True, null=True, verbose_name='Fundo de Olho (Data)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='fundo_olho_resultado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fundo de Olho (Resultado)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='gpa_a',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Aborto (A)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='gpa_g',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gesta (G)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='gpa_p',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Para (P)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='ig_dias',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='IG na Alta (Dias)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='ig_semanas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='IG na Alta (Semanas)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='npp_d',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='NPP (dias)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='peso_adequacao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Adequação Peso/IG (PIG/AIG/GIG)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='peso_alta',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso na Alta (g)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='profilaxia_bolsa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Profilaxia Adequada (Bolsa Rota)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='reanimacao_obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da Reanimação'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='reanimacao_opcoes',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Manobras de Reanimação (JSON)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='reanimacao_status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Houve Reanimação (Sim/Não)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='rh_mae',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Rh Mãe'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='rh_rn',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Rh RN'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='suporte_cpap_d',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CPAP (dias)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='suporte_o2_d',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='O2 Suplementar (dias)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='suporte_vm_d',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ventilação Mecânica (dias)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='tipo_sanguineo_rn',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Sanguíneo RN'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='us_tf_data',
            field=models.DateField(blank=True, null=True, verbose_name='US Transfontanelar (Data)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='us_tf_resultado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='US Transfontanelar (Resultado)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='vicios',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Vícios Maternos (Sim/Não)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='vicios_detalhes',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Vícios Maternos (JSON)'),
        ),
        migrations.AddField(
            model_name='anamneseneonatologia',
            name='vicios_outros_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição de Outros Vícios'),
        ),
        migrations.AddField(
            model_name='anamnesepediatria',
            name='triagens',
            field=models.JSONField(blank=True, default=dict, help_text='JSON com chaves: pezinho_status/desc, orelhinha_eoat_status/desc, orelhinha_bera_status/desc, olhinho_status/desc, coracaozinho_status/desc, linguinha_status/desc', null=True),
        ),
    ]
