# Generated by Django 5.0.7 on 2026-07-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0044_anamneseneonatologia_anti_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudo',
            name='tipo_exame',
            field=models.CharField(default='OBSTETRICO', max_length=255),
        ),
    ]
