# Generated by Django 5.0.7 on 2026-09-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0045_alter_laudo_tipo_exame'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='feedback_auditoria',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PROCESSANDO', 'Processando'), ('REVISAO_SUGERIDA', 'Revisão Sugerida'), ('FINALIZADO', 'Finalizado'), ('ERRO', 'Erro'), ('CANCELADO_POR_RETIFICACAO', 'Cancelado (Retificado)')], default='RASCUNHO', max_length=50),
        ),
    ]
