# Generated by Django 5.0.7 on 2026-01-23 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0013_sala_e_sala_exame_sala_equipamentos_and_more'),
        ('pacientes', '0008_alter_paciente_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseComportamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_emocional', models.CharField(choices=[('TRANQUILA', 'Tranquila'), ('INSEGURA', 'Insegura'), ('ANSIOSA', 'Ansiosa'), ('DECIDIDA', 'Decidida'), ('INDEFINIDO', 'Indefinido')], default='INDEFINIDO', max_length=20)),
                ('principal_objecao', models.CharField(blank=True, choices=[('PRECO', 'Preço'), ('AGENDA', 'Agenda/Horário'), ('MEDICO', 'Preferência por Médico'), ('DISTANCIA', 'Distância'), ('MEDO', 'Medo do Exame'), ('OUTRO', 'Outro')], max_length=20, null=True)),
                ('observacoes_internas', models.TextField(blank=True, help_text='Informações cruciais para a equipe de atendimento')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_comportamental', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GESTACAO', 'Gestação'), ('RN', 'Recém-Nascido'), ('PEDIATRIA', 'Pediatria'), ('CARDIO', 'Cardiologia'), ('OUTRO', 'Outro')], default='GESTACAO', max_length=20)),
                ('fase_atual', models.CharField(choices=[('F1', 'F1 - Entrada'), ('F2', 'F2 - Conversão'), ('F3', 'F3 - Pós-Exame'), ('F4', 'F4 - Retenção'), ('ENCERRADO', 'Ciclo Encerrado')], default='F1', max_length=20)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_encerramento', models.DateTimeField(blank=True, null=True)),
                ('receita_acumulada', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('qtd_atendimentos', models.IntegerField(default=0)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='pacientes.paciente')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ciclo de Cuidado',
                'verbose_name_plural': 'Ciclos de Cuidado',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ProximaAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Ligar para agendar Morfológico', max_length=255)),
                ('data_alvo', models.DateField(help_text='Quando essa ação deve acontecer?')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('ATRASADA', 'Atrasada')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('realizado_em', models.DateTimeField(blank=True, null=True)),
                ('agendamento_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acao_origem', to='agendamentos.agendamento')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='crm.ciclo')),
            ],
        ),
    ]
