# Generated by Django 5.0.7 on 2026-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='nivel_risco',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('ALERTA', 'Alerta (Atraso leve)'), ('CRITICO', 'Crítico (Risco de Evasão)')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='origem',
            field=models.CharField(blank=True, help_text='Cópia da origem do paciente para facilitar filtros', max_length=50, null=True),
        ),
    ]
