# Generated by Django 5.0.7 on 2026-01-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_ciclo_nivel_risco_ciclo_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado')], default='ativo', max_length=20),
        ),
    ]
