# Generated by Django 5.0.7 on 2026-02-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_ciclo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='data_dum',
            field=models.DateField(blank=True, help_text='Essencial para o cálculo automático de exames previstos', null=True, verbose_name='Data da Última Menstruação (DUM)'),
        ),
    ]
