# Generated by Django 5.0.7 on 2026-02-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_ciclo_data_dum'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecomportamental',
            name='avaliou_google',
            field=models.BooleanField(default=False, verbose_name='Fez avaliação no Google?'),
        ),
        migrations.AddField(
            model_name='analisecomportamental',
            name='indicou_outros',
            field=models.BooleanField(default=False, verbose_name='Indicou alguém depois?'),
        ),
        migrations.AddField(
            model_name='analisecomportamental',
            name='origem_aquisicao',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'Google (Pesquisa/Meu Negócio)'), ('INSTAGRAM', 'Instagram'), ('INDICACAO', 'Indicação de Paciente/Amigo'), ('MEDICO', 'Indicação Médica'), ('CONVENIO', 'Convênio'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Como conheceu a clínica?'),
        ),
        migrations.AddField(
            model_name='analisecomportamental',
            name='segue_instagram',
            field=models.BooleanField(default=False, verbose_name='Segue no Instagram?'),
        ),
    ]
