# Generated by Django 5.0.7 on 2026-03-06 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_analisecomportamental_avaliou_google_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proximaacao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proximaacao',
            name='responsavel',
            field=models.ForeignKey(blank=True, help_text='Quem deve executar esta ação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='fase_atual',
            field=models.CharField(choices=[('F1', 'F1 - Entrada'), ('F2', 'F2 - Conversão'), ('F3', 'F3 - Pós-Exame'), ('F4', 'F4 - Retenção'), ('F5', 'F5 - Recuperação'), ('ENCERRADO', 'Ciclo Encerrado')], default='F1', max_length=20),
        ),
    ]
