# Generated by Django 5.0.7 on 2026-06-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_proximaacao_atualizado_em_proximaacao_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecomportamental',
            name='origem_aquisicao',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'Google (Pesquisa/Meu Negócio)'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook Ads'), ('TIKTOK', 'TikTok'), ('SITE', 'Site Oficial'), ('INDICACAO', 'Indicação de Paciente/Amigo'), ('MEDICO', 'Indicação Médica'), ('CONVENIO', 'Convênio'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Como conheceu a clínica?'),
        ),
    ]
