# Generated by Django 5.0.7 on 2026-06-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_analisecomportamental_origem_aquisicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecomportamental',
            name='concorrencia_mencionada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Concorrente Mencionado'),
        ),
        migrations.AddField(
            model_name='analisecomportamental',
            name='exame_interesse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Exame de Interesse (Bot)'),
        ),
        migrations.AddField(
            model_name='analisecomportamental',
            name='medico_solicitante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Médico que pediu o exame'),
        ),
        migrations.AddField(
            model_name='analisecomportamental',
            name='motivo_exame',
            field=models.CharField(blank=True, choices=[('rotina', 'Rotina'), ('investigacao_dor', 'Investigação/Dor'), ('acompanhamento', 'Acompanhamento'), ('urgencia', 'Urgência')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analisecomportamental',
            name='nivel_urgencia',
            field=models.CharField(choices=[('frio', 'Frio'), ('morno', 'Morno'), ('quente', 'Quente')], default='morno', max_length=20),
        ),
        migrations.AddField(
            model_name='analisecomportamental',
            name='primeira_gravidez',
            field=models.BooleanField(blank=True, null=True, verbose_name='Mãe de Primeira Viagem?'),
        ),
        migrations.AddField(
            model_name='analisecomportamental',
            name='sexo_bebe',
            field=models.CharField(blank=True, choices=[('menino', 'Menino'), ('menina', 'Menina'), ('surpresa', 'Surpresa')], max_length=20, null=True),
        ),
    ]
