# Generated by Django 5.0.7 on 2026-08-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_analisecomportamental_concorrencia_mencionada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecomportamental',
            name='bairro_interesse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analisecomportamental',
            name='cidade_interesse',
            field=models.CharField(blank=True, help_text='Extraído da conversa ou IP', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analisecomportamental',
            name='especialidade_interesse',
            field=models.CharField(blank=True, help_text='Cardio, Pediatria, Ginecologia, etc.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analisecomportamental',
            name='principal_objecao',
            field=models.CharField(blank=True, choices=[('PRECO', 'Preço / Valor do Exame'), ('FORMA_PAGAMENTO', 'Forma de Pagamento'), ('AGENDA', 'Agenda / Falta de Horário'), ('LOCALIZACAO', 'Localização / Distância'), ('CONVENIO', 'Convênio Não Aceito'), ('ATENDIMENTO', 'Insatisfação no Atendimento'), ('CURIOSIDADE', 'Curiosidade / Pesquisa'), ('MEDICO', 'Preferência por outro Médico'), ('MEDO', 'Medo do Exame'), ('OUTRO', 'Outro')], max_length=30, null=True),
        ),
    ]
