# Generated by Django 5.0.7 on 2026-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_analisecomportamental_bairro_interesse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='macro_area',
            field=models.CharField(choices=[('GERAL', 'Ultrassonografia Geral'), ('FETAL', 'Medicina Fetal')], default='GERAL', max_length=10),
        ),
    ]
