# Generated by Django 5.0.7 on 2026-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, unique=True)),
                ('total_entradas', models.IntegerField(default=0)),
                ('total_agendados', models.IntegerField(default=0)),
                ('total_compareceram', models.IntegerField(default=0)),
                ('total_retencao', models.IntegerField(default=0)),
                ('receita_do_dia', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ticket_medio_dia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pacientes_em_risco', models.IntegerField(default=0, help_text='Qtd de pacientes com atraso na jornada')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MetaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Dia 1 do mês de referência')),
                ('investimento_marketing', models.DecimalField(decimal_places=2, default=0.0, help_text='Total investido em Ads/Mkt no mês', max_digits=12)),
                ('custos_fixos_estimados', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('meta_faturamento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('meta_novos_ciclos', models.IntegerField(default=50)),
                ('meta_conversao', models.DecimalField(decimal_places=2, default=20.0, help_text='Em %', max_digits=5)),
            ],
            options={
                'verbose_name': 'Meta e Investimento Mensal',
                'unique_together': {('mes_referencia',)},
            },
        ),
    ]
