# Generated by Django 5.0.7 on 2025-11-23 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0007_paciente_cpf_responsavel_paciente_nome_responsavel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloLaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('codigo_procedimento', models.CharField(blank=True, help_text='Código TUSS ou interno para puxar automaticamente ao agendar', max_length=50, null=True)),
                ('conteudo_padrao', models.JSONField(default=dict)),
                ('especialidade', models.CharField(default='Radiologia', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento_id', models.IntegerField(blank=True, null=True)),
                ('titulo_exame', models.CharField(max_length=255)),
                ('conteudo_laudo', models.JSONField(default=dict)),
                ('texto_puro', models.TextField(blank=True)),
                ('imagens_selecionadas', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ASSINADO', 'Assinado/Finalizado')], default='RASCUNHO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laudos_realizados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudos', to='pacientes.paciente')),
            ],
        ),
    ]
