# Generated by Django 5.0.7 on 2025-11-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelolaudo',
            name='conteudo_padrao',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
