# Generated by Django 5.0.7 on 2025-11-24 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0013_sala_e_sala_exame_sala_equipamentos_and_more'),
        ('laudos', '0002_alter_modelolaudo_conteudo_padrao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laudo',
            name='agendamento_id',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='imagens_selecionadas',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='modelolaudo',
            name='codigo_procedimento',
        ),
        migrations.AddField(
            model_name='laudo',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laudo', to='agendamentos.agendamento'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laudo',
            name='hash_assinatura',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='laudo',
            name='imagens_ids',
            field=models.JSONField(blank=True, default=list, help_text='Lista de InstanceUIDs do DICOM selecionados'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='medico_executante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laudos_assinados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelolaudo',
            name='codigo_mnemonico',
            field=models.CharField(blank=True, help_text='Ex: USG-OBS-GEMELAR', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modelolaudo',
            name='texto_padrao_html',
            field=models.TextField(blank=True, help_text='Versão HTML simples se não usar editor rico'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('REVISAO', 'Em Revisão'), ('ASSINADO', 'Assinado/Finalizado')], default='RASCUNHO', max_length=20),
        ),
    ]
