# Generated by Django 5.0.7 on 2025-11-28 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0013_sala_e_sala_exame_sala_equipamentos_and_more'),
        ('laudos', '0003_remove_laudo_agendamento_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laudo',
            old_name='medico_executante',
            new_name='medico',
        ),
        migrations.RenameField(
            model_name='laudo',
            old_name='texto_puro',
            new_name='texto_laudo',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='conteudo_laudo',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='data_assinatura',
        ),
        migrations.RemoveField(
            model_name='laudo',
            name='hash_assinatura',
        ),
        migrations.RemoveField(
            model_name='modelolaudo',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='laudo',
            name='dados_estruturados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laudo', to='agendamentos.agendamento'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='imagens_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelolaudo',
            name='codigo_mnemonico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelolaudo',
            name='texto_padrao_html',
            field=models.TextField(blank=True),
        ),
    ]
