# Generated by Django 5.0.7 on 2026-01-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0004_rename_medico_executante_laudo_medico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='codigo_acesso',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='laudo',
            name='crm_medico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='laudo',
            name='senha_acesso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='laudo',
            name='tipo_exame',
            field=models.CharField(default='OBSTETRICO', max_length=50),
        ),
    ]
