# Generated by Django 5.0.7 on 2026-01-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0005_laudo_codigo_acesso_laudo_crm_medico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='laudos_assinados/%Y/%m/', verbose_name='Arquivo PDF Assinado'),
        ),
    ]
