# Generated by Django 5.0.7 on 2026-02-09 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_exame_ciclo'),
        ('laudos', '0006_laudo_arquivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='exame',
            field=models.OneToOneField(blank=True, help_text='Vínculo com os arquivos e credenciais do portal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laudo_medico', to='exames.exame'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='medico_responsavel',
            field=models.CharField(blank=True, help_text='Nome do médico exibido na assinatura/lista', max_length=255, null=True),
        ),
    ]
