# Generated by Django 5.0.7 on 2025-12-02 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0007_paciente_cpf_responsavel_paciente_nome_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exame', models.DateField()),
                ('nome_paciente_pasta', models.CharField(help_text='Nome que veio escrito na pasta do ultrassom', max_length=255)),
                ('codigo_acesso', models.CharField(blank=True, max_length=20, unique=True)),
                ('senha_acesso', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Vínculo'), ('DISPONIVEL', 'Disponível no Portal')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='exames/%Y/%m/%d/')),
                ('tipo', models.CharField(choices=[('IMAGEM', 'Imagem'), ('VIDEO', 'Vídeo'), ('LAUDO', 'Laudo')], max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='exames.exame')),
            ],
        ),
    ]
