# Generated by Django 5.0.7 on 2026-01-12 22:38

import exames.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoexame',
            name='arquivo',
            field=models.FileField(upload_to=exames.models.diretorio_laudos),
        ),
        migrations.AlterField(
            model_name='exame',
            name='nome_paciente_pasta',
            field=models.CharField(help_text='Nome na pasta do ultrassom', max_length=255),
        ),
    ]
