# Generated by Django 5.0.7 on 2026-02-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_exame_ciclo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exame',
            unique_together={('nome_paciente_pasta', 'data_exame')},
        ),
    ]
