# Generated by Django 5.0.7 on 2026-06-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0004_alter_exame_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='codigo_acesso',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
