# Generated by Django 5.0.7 on 2026-09-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0005_alter_exame_codigo_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Vínculo'), ('DISPONIVEL', 'Disponível no Portal'), ('ERRO', 'Erro de Sincronização')], default='PENDENTE', max_length=20),
        ),
    ]
