# Generated by Django 5.0.7 on 2025-09-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmemory',
            name='state',
            field=models.CharField(blank=True, default='inicio', max_length=100, null=True),
        ),
    ]
