# Generated by Django 5.0.7 on 2025-10-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmemory_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmemory',
            name='previous_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatmemory',
            name='memory_data',
            field=models.JSONField(default=dict),
        ),
    ]
