# Generated by Django 5.0.7 on 2025-10-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatmemory_previous_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmemory',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Memória de Conversa', 'verbose_name_plural': 'Memórias de Conversas'},
        ),
        migrations.CreateModel(
            name='ChatbotMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('evento', models.CharField(max_length=100)),
                ('dados_evento', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métrica do Chatbot',
                'verbose_name_plural': 'Métricas do Chatbot',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['evento', 'timestamp'], name='chatbot_cha_evento_e04be6_idx'), models.Index(fields=['session_id', 'timestamp'], name='chatbot_cha_session_0b539b_idx')],
            },
        ),
    ]
