# Generated by Django 5.0.7 on 2025-10-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_add_conversation_control_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmemory',
            new_name='chatbot_cha_transfe_fec5b0_idx',
            old_name='chatbot_chatmemory_transfer_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmemory',
            new_name='chatbot_cha_convers_876c8c_idx',
            old_name='chatbot_chatmemory_encerrada_idx',
        ),
    ]
