# Generated by Django 5.0.7 on 2025-09-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_especialidade_customuser_especialidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='crm',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CRM'),
        ),
        migrations.AddField(
            model_name='especialidade',
            name='valor_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Consulta Particular'),
        ),
    ]
