# Generated by Django 5.0.7 on 2025-09-26 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser_crm_especialidade_valor_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaDeTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('medico', models.ForeignKey(limit_choices_to={'cargo': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='jornadas_de_trabalho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jornada de Trabalho',
                'verbose_name_plural': 'Jornadas de Trabalho',
                'unique_together': {('medico', 'dia_da_semana', 'hora_inicio')},
            },
        ),
    ]
