# Generated by Django 5.0.7 on 2025-12-15 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_customuser_bairro_customuser_cep_customuser_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_p12', models.FileField(upload_to='certificados_digitais/')),
                ('senha_criptografada', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
