# Generated by Django 5.0.7 on 2026-02-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_certificadomedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadomedico',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração'),
        ),
    ]
