# Generated by Django 5.0.7 on 2026-04-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_certificadomedico_data_expiracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadadetrabalho',
            name='semanas_do_mes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
