# Generated by Django 5.0.7 on 2026-05-18 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0023_lotefaturamento_data_pagamento_and_more'),
        ('usuarios', '0012_jornadadetrabalho_semanas_do_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorEspecialidadeConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_convenio', to='usuarios.especialidade')),
                ('plano_convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faturamento.planoconvenio')),
            ],
            options={
                'verbose_name': 'Valor de Especialidade por Convênio',
                'unique_together': {('especialidade', 'plano_convenio')},
            },
        ),
    ]
