# Generated by Django 5.0.7 on 2026-06-11 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_valorespecialidadeconvenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin_ponto',
            field=models.CharField(blank=True, help_text='PIN numérico de 4 a 6 dígitos para o ponto eletrônico', max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida_pausa', 'Saída para Pausa/Almoço'), ('retorno_pausa', 'Retorno da Pausa'), ('saida', 'Saída (Fim do expediente)')], max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distancia_metros', models.FloatField(blank=True, null=True, verbose_name='Distância do centro (m)')),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado (Dentro do Raio)'), ('rejeitado', 'Rejeitado (Fora do Raio)'), ('ajuste_manual', 'Ajuste Manual (RH)')], default='aprovado', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Navegador/Dispositivo usado', null=True)),
                ('observacao', models.TextField(blank=True, help_text='Justificativas ou notas do RH', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-data_hora'],
            },
        ),
    ]
