# Generated by Django 5.0.7 on 2026-06-14 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_configuracaoclinica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='especialidades',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rqe',
        ),
        migrations.CreateModel(
            name='MedicoEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rqe', models.CharField(blank=True, max_length=20, null=True, verbose_name='RQE')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.especialidade')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_especialidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Especialidade do Profissional',
                'verbose_name_plural': 'Especialidades do Profissional',
                'unique_together': {('medico', 'especialidade')},
            },
        ),
    ]
