# Generated by Django 5.0.7 on 2026-06-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_remove_customuser_especialidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='especialidades',
            field=models.ManyToManyField(blank=True, through='usuarios.MedicoEspecialidade', to='usuarios.especialidade', verbose_name='Especialidades do Profissional'),
        ),
    ]
