# Generated by Django 5.0.7 on 2026-06-15 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_customuser_especialidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='status',
            field=models.CharField(choices=[('aprovado', 'Aprovado (Dentro do Raio)'), ('rejeitado', 'Rejeitado (Fora do Raio)'), ('ajuste_manual', 'Ajuste Manual (RH)'), ('cancelado', 'Cancelado (RH)')], default='aprovado', max_length=20),
        ),
    ]
