# Generated by Django 5.0.7 on 2026-08-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_registroponto_data_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='digital_template',
            field=models.TextField(blank=True, help_text='Mapa de minúcias da digital (SourceAFIS) em Base64', null=True),
        ),
    ]
