# Generated by Django 5.0.7 on 2026-08-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_customuser_digital_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoclinica',
            name='recepcao_ve_configuracoes',
            field=models.BooleanField(default=False, verbose_name='Permitir que a recepção acesse as configurações'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='digital_template',
            field=models.TextField(blank=True, help_text='Template da digital gerado pelo SDK da Futronic', null=True),
        ),
    ]
