# Generated by Django 5.0.7 on 2026-08-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_configuracaoclinica_recepcao_ve_configuracoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoclinica',
            name='recepcao_ve_configuracoes',
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='recepcao_ve_clinica',
            field=models.BooleanField(default=False, verbose_name='Recepção vê Aba Clínica'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='recepcao_ve_equipe',
            field=models.BooleanField(default=False, verbose_name='Recepção vê Aba Equipe'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='recepcao_ve_financeiro',
            field=models.BooleanField(default=False, verbose_name='Recepção vê Aba Financeiro'),
        ),
    ]
