# Generated by Django 5.0.7 on 2026-09-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_remove_configuracaoclinica_recepcao_ve_configuracoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('medico', 'Médico'), ('admin_medico', 'Médico Sócio (Admin/Médico)')], default='recepcao', max_length=15),
        ),
    ]
