# Generated by Django 5.0.7 on 2026-09-08 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_customuser_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadadetrabalho',
            name='medico',
            field=models.ForeignKey(limit_choices_to={'cargo__in': ['medico', 'admin_medico']}, on_delete=django.db.models.deletion.CASCADE, related_name='jornadas_de_trabalho', to=settings.AUTH_USER_MODEL),
        ),
    ]
