# Generated by Django 5.0.7 on 2025-12-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome da Clínica', max_length=255)),
                ('endereco', models.CharField(blank=True, max_length=500)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('logo_path', models.CharField(blank=True, help_text="Caminho estático para o logo, ex: 'images/logo.png'", max_length=255)),
            ],
            options={
                'verbose_name': 'Configuração da Clínica',
                'verbose_name_plural': 'Configurações da Clínica',
            },
        ),
    ]
