# Generated by Django 5.0.7 on 2025-12-02 17:32

from django.db import migrations
from django.conf import settings


def forwards_func(apps, schema_editor):
    """
    Carrega os dados de CLINICA_INFO do settings.py para o modelo ConfiguracaoClinica.
    """
    ConfiguracaoClinica = apps.get_model('core', 'ConfiguracaoClinica')
    
    # O settings.CLINICA_INFO ainda existe neste ponto da execução.
    # Usamos os valores dele para popular o banco de dados pela primeira vez.
    if hasattr(settings, 'CLINICA_INFO'):
        info = settings.CLINICA_INFO
        ConfiguracaoClinica.objects.update_or_create(
            pk=1,
            defaults={
                'nome': info.get('NOME', 'Nome Padrão'),
                'endereco': info.get('ENDERECO', ''),
                'telefone': info.get('TELEFONE', ''),
                'email': info.get('EMAIL', ''),
                'logo_path': info.get('LOGO_STATIC_PATH', ''),
            }
        )

def backwards_func(apps, schema_editor):
    """
    Função reversa. Não faz nada, pois não queremos apagar os dados se a migração for revertida.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
