# Generated by Django 5.0.7 on 2025-12-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251202_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Clinica Limalé - Especialidades Médicas e Imagem', max_length=255)),
                ('endereco', models.CharField(default='R. Orense, 41 - sala 512, Edifício D - Office, Diadema - SP, 09920-650', max_length=500)),
                ('telefone', models.CharField(default='(11) 919511842', max_length=20)),
                ('email', models.EmailField(default='contato@limale.com.br', max_length=254)),
                ('logo', models.CharField(default='images/logo_limale.jpg', help_text='Caminho para o logo a partir do diretório static.', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ConfiguracaoClinica',
        ),
    ]
