# Generated by Django 5.0.7 on 2025-08-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('faturamento', '0004_convenio_planoconvenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='plano_utilizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faturamento.planoconvenio', verbose_name='Plano Utilizado no Agendamento'),
        ),
    ]
