# Generated by Django 5.0.7 on 2025-08-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_agendamento_plano_utilizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='tipo_atendimento',
            field=models.CharField(choices=[('Convenio', 'Convênio'), ('Particular', 'Particular')], default='Particular', max_length=10),
        ),
    ]
