# Generated by Django 5.0.7 on 2025-08-23 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_agendamento_tipo_atendimento'),
        ('pacientes', '0005_remove_paciente_convenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='pacientes.paciente'),
        ),
    ]
