# Generated by Django 5.0.7 on 2025-08-24 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_alter_agendamento_paciente'),
        ('faturamento', '0007_procedimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faturamento.procedimento'),
        ),
    ]
