# Generated by Django 5.0.7 on 2025-08-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_agendamento_procedimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='id_sala_telemedicina',
            field=models.CharField(blank=True, help_text='ID da sala retornado pela API de vídeo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='link_telemedicina',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link da Sala de Telemedicina'),
        ),
    ]
