# Generated by Django 5.0.7 on 2025-09-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_agendamento_id_sala_telemedicina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('Presencial', 'Presencial'), ('Telemedicina', 'Telemedicina')], default='Presencial', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tipo_visita',
            field=models.CharField(blank=True, choices=[('Primeira Consulta', 'Primeira Consulta'), ('Retorno', 'Retorno')], default='Primeira Consulta', max_length=20, null=True),
        ),
    ]
