# Generated by Django 5.0.7 on 2025-09-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_agendamento_modalidade_agendamento_tipo_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='expira_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira em'),
        ),
    ]
