# Generated by Django 5.0.7 on 2025-09-07 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_agendamento_expira_em'),
        ('usuarios', '0003_customuser_crm_especialidade_valor_consulta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='tipo_consulta',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.especialidade'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='medico',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'medico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_como_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tipo_agendamento',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Procedimento', 'Procedimento')], default='Consulta', max_length=20),
        ),
    ]
