# Generated by Django 5.0.7 on 2025-10-08 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_remove_agendamento_tipo_consulta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Consultório 1, Sala de Ultrassom', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Qualquer detalhe adicional sobre a sala.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='agendamentos.sala', verbose_name='Sala de Atendimento'),
        ),
    ]
