# Generated by Django 5.0.7 on 2025-10-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_sala_agendamento_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('Aguardando', 'Aguardando na Recepção'), ('Em Atendimento', 'Em Atendimento'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado'), ('Não Compareceu', 'Não Compareceu')], default='Agendado', max_length=20),
        ),
    ]
