# Generated by Django 5.0.7 on 2025-10-24 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0011_alter_agendamento_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Início do Bloqueio')),
                ('data_fim', models.DateTimeField(verbose_name='Fim do Bloqueio')),
                ('motivo', models.CharField(blank=True, help_text='Ex: Férias, Congresso, Almoço', max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(limit_choices_to={'cargo': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueio de Agenda',
                'verbose_name_plural': 'Bloqueios de Agenda',
                'ordering': ['data_inicio'],
            },
        ),
    ]
