# Generated by Django 5.0.7 on 2025-11-24 01:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0012_bloqueioagenda'),
        ('faturamento', '0011_pagamento_descricao'),
        ('laudos', '0002_alter_modelolaudo_conteudo_padrao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='e_sala_exame',
            field=models.BooleanField(default=False, verbose_name='É sala de exames?'),
        ),
        migrations.AddField(
            model_name='sala',
            name='equipamentos',
            field=models.CharField(blank=True, help_text='Tags separadas por vírgula. Ex: SAMSUNG_V7, DOPPLER, 4D', max_length=255),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_como_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='agendamentos.sala'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('Aguardando', 'Aguardando na Recepção'), ('Em Atendimento', 'Em Atendimento'), ('Laudando', 'Em Processo de Laudo'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado'), ('Não Compareceu', 'Não Compareceu')], default='Agendado', max_length=20),
        ),
        migrations.AlterField(
            model_name='sala',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(help_text='Ex: Sala 1 - Ultrassom Samsung', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ConfiguracaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao_padrao', models.DurationField(default=datetime.timedelta(seconds=1200))),
                ('equipamento_obrigatorio', models.CharField(blank=True, help_text='Ex: SAMSUNG_V7. Se preenchido, só agenda em salas com esse equipamento.', max_length=50, null=True)),
                ('modelo_laudo_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimentos_associados', to='laudos.modelolaudo')),
                ('procedimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_clinica', to='faturamento.procedimento')),
            ],
        ),
    ]
