# Generated by Django 5.0.7 on 2026-01-23 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0013_sala_e_sala_exame_sala_equipamentos_and_more'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='ciclo',
            field=models.ForeignKey(blank=True, help_text='A qual ciclo de cuidado este agendamento pertence?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='crm.ciclo'),
        ),
    ]
