# Generated by Django 5.0.7 on 2026-03-20 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0014_agendamento_ciclo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaFuncionamentoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('hora_inicio', models.TimeField(default='08:00', verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(default='18:00', verbose_name='Hora de Fim')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_funcionamento', to='agendamentos.configuracaoexame')),
            ],
            options={
                'verbose_name': 'Dia de Funcionamento',
                'verbose_name_plural': 'Dias de Funcionamento',
                'unique_together': {('configuracao', 'dia_semana')},
            },
        ),
    ]
