# Generated by Django 5.0.7 on 2026-07-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0015_diafuncionamentoexame'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='is_encaixe',
            field=models.BooleanField(default=False, help_text='Marcado automaticamente quando o agendamento é salvo sobrepondo um conflito real de sala/capacidade.', verbose_name='É encaixe?'),
        ),
    ]
