# Generated by Django 5.0.7 on 2026-08-29 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0016_agendamento_is_encaixe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='detalhes_pendencia',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da Pendência (Outros)'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='hora_checkin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora do Check-in'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='hora_finalizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de Finalização'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='hora_inicio_atendimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de Início do Atendimento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='pendencia_administrativa',
            field=models.BooleanField(default=False, verbose_name='Pendente: Administrativa'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='pendencia_declaracao',
            field=models.BooleanField(default=False, verbose_name='Pendente: Declaração/Atestado'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='pendencia_intercorrencia',
            field=models.BooleanField(default=False, verbose_name='Pendente: Intercorrência'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='pendencia_laudo',
            field=models.BooleanField(default=False, verbose_name='Pendente: Laudo'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='pendencia_reclamacao',
            field=models.BooleanField(default=False, verbose_name='Pendente: Reclamação'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='responsavel_atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_iniciados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Atendimento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='responsavel_checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Check-in'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='responsavel_finalizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_finalizados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Finalização'),
        ),
    ]
