# Generated by Django 5.0.7 on 2026-09-08 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0017_agendamento_detalhes_pendencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='medico',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo__in': ['medico', 'admin_medico']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_como_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloqueioagenda',
            name='medico',
            field=models.ForeignKey(limit_choices_to={'cargo__in': ['medico', 'admin_medico']}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
